## Write a Numpy program to compute the multiplication of two given matrixes

In [21]:
import numpy as np
def MulArr(A,B):
    return np.multiply(A,B)

In [23]:
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
MulArr(A,B)

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

## Write a NumPy program to compute the determinant of a given square array

In [5]:
def Determinant(A):
    return np.linalg.det(A)

In [7]:
Determinant(np.array([[1,2],[4,5]]))

-2.9999999999999996

## Write a NumPy program to compute the cross product of two given vectors

In [27]:
def crossproduct(A,B):
    return np.cross(A,B)

In [28]:
A = np.array([1,2])
B = np.array([3,4])
crossproduct(A,B)

array(-2)

## Write a NumPy program to compute the condition number of a given matrix

In [31]:
def ConditionMatrix(A):
    return np.linalg.cond(A)

In [32]:
ConditionMatrix(np.matrix([[1,2],[3,4]]))

14.933034373659265

## Write a NumPy program to compute the inverse of a given matrix

In [9]:
def inverse(A):
    return np.linalg.inv(A)

In [25]:
a = np.matrix([[ 5, 10], [ 15, 20 ]])
b = inverse(a)
b

matrix([[-0.4,  0.2],
        [ 0.3, -0.1]])

In [26]:
I = a.dot(b)
I

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])